### ISSUE TITLE
Performance improvement for directory listing

### ISSUE THREAD

**Issue by animosity22** [dweidenfeld/plexdrive#13] opened 2017-05-05 17:36 UTC
I was trying to figure out if this was the fact that auto_cache isn't available, but I would expect a full 'ls' to pick up some speedy after it knows about all the files/metadata for them.

I did a few tests ls commands and they seem to take roughly 5 minutes to come back compared to maybe 30 seconds for the first using ocamlfuse and than I think auto_cache kicks in and it takes less than s second after that.

```
felix@plex:~/test/media/smu5ej34ujbdoip1cm3mlk92q4$ time ls -alR | wc -l
14625

real	5m29.055s
user	0m0.180s
sys	0m0.212s
```

This helps for when I want to kick off a full scan or something in plex as it just checks files and their modtimes to validate if it needs to scan it or not.

**Comment by dweidenfeld** [comment] 2017-05-06 08:44
I think it is more a problem with the current implementation of the caching.
I got some ideas to improve the speed, even without using the auto_cache option.

I will put this issue in the backlog and try to implement a faster directory listing for the next release.

**Comment by francesco2013** [comment] 2017-05-07 15:16
First of all thanks for your nice work @dweidenfeld :) 

I have to agree that the file listing is so slow that sometimes you cant even add the directory to plex cause it takes so long to list the content that Plex times out. 

I am very interested in this project I hope the next release will fix this :)

**Comment by cmeka** [comment] 2017-05-08 14:09
```time ls -alR | wc -l
79210
real    28m52.661s
user    0m1.894s
sys     0m4.168s```

I wouldn't mind 5min, still I'm thrilled to find out about this project. So much potential and it works great as is. Thank you dweidenfeld!

**Comment by dweidenfeld** [comment] 2017-05-09 07:00
@cmeka how many files do you have in your biggest folder?

```
$ ls -1 | wc -l
104
```

**Comment by dweidenfeld** [comment] 2017-05-09 12:32
Latest dev version shows this stats on my pc
```
# time ls -laR|wc -l
64698
ls --group-directories-first --color=auto -laR  0.57s user 1.01s system 1% cpu 2:03.82 total
wc -l  0.00s user 0.01s system 0% cpu 2:03.81 total
```

2:03 minutes for ~65k files. Is this ok for you?

**Comment by xyber411** [comment] 2017-05-09 12:33
My largest folder when properly sorted will have 2,300+ folders inside of it, and under 10 files in each of those folders including one large file.

**Comment by azgul** [comment] 2017-05-09 13:00
I think performance would be increased quite a lot if you fix the typo in the APIObject struct:
```
Parents      string `grom:"index"
```

**Comment by dweidenfeld** [comment] 2017-05-09 13:05
@azgul thx, done ;)

@xyber411 
Maybe there will be a release later today. 
I would like to have #22 in the next release. So still waiting for @kilabyte :laughing: ... If his version is not ready till ~19:00 (GMT+1) I will provide a new release, ok?

**Comment by xyber411** [comment] 2017-05-09 13:17
LOL You don't have to ask me!!! I do appreciate the feedback though!

**Comment by dweidenfeld** [comment] 2017-05-09 13:19
This is my project, but I think it will grow better with a great community, so your feedback is gold to me ;)

**Comment by dweidenfeld** [comment] 2017-05-09 13:24
After the typo fix
```
# time ls -laR|wc -l
64698
ls --group-directories-first --color=auto -laR  0.56s user 1.34s system 1% cpu 1:50.96 total
wc -l  0.01s user 0.00s system 0% cpu 1:50.96 total
```

**Comment by dweidenfeld** [comment] 2017-05-09 13:27
I don't think we will get much more speed without changing the cache database. 
My first idea was to use tiedot (https://github.com/HouzuoGuo/tiedot) as NoSQL datastore, but the problem is with indexing array fields. I opened an issue https://github.com/HouzuoGuo/tiedot/issues/130 ... as soon as this issue is resolved, I will try to change the database to tiedot and check if it increases the performance.

So I close this issue because the discussed changes are prepared for the next release.

**Closed by dweidenfeld** 2017-05-09 13:27 UTC
Labels: enhancement

**Comment by animosity22** [comment] 2017-05-09 17:34
It's definitely much much better now and very usable.

```
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$ time ls -alR | wc -l
14672

real	0m10.555s
user	0m0.040s
sys	0m0.164s
```

and the fuse mount once it runs once is faster than before:
```
felix@plex:/TV$ time ls -alR | wc -l
14993

real	0m14.726s
user	0m0.044s
sys	0m0.084s
felix@plex:/TV$ time ls -alR | wc -l
14993

real	0m0.574s
user	0m0.060s
sys	0m0.052s
```

Good stuff!
