### ISSUE TITLE
Plexdrive not using chunks in cache?

### ISSUE THREAD

**Issue by ladude626** [dweidenfeld/plexdrive#166] opened 2017-06-08 19:24 UTC
I'm currently running Plexdrive 4.0 beta with mongodb compiled by @zenjabba from the Slack support channel, which should be the master branch on github as of 6/8/17 . When I read a file the 1st time the speed is about 14MB/s. When I read it a 2nd time, the speed is exactly the same at 14MB/s and not any faster. It looks like Plexdrive is not using the chunks from the local cache at all. When I check the network with iftop, the server is connecting to and downloading from Google Drive again during the 2nd read.

EDIT: Here are my mount options

    plexdrive -v 2 --clear-chunk-max-size=300G --chunk-size=8M -o allow_other -t /mnt/plexdrive-cache --refresh-interval=5m -m localhost /mnt/plexdrive

I did this on a new install. And after the 1st read I can see the chunks inside the cache folder.

**Comment by dweidenfeld** [comment] 2017-06-09 05:51
Please check the /mnt/plexdrive-cache directory. Maybe plexdrive doesn't have write access or maybe the read requests are "too fast", so that the chunk files have not been written but are requested again.

I cannot reproduce the issue, but after the release of version 4.0.0 I will have to refactor the playback/chunking/buffer logic because there are soo many problems with macOS currently. I cannot give you a date when this bug will be fixed, but I am working on it ;)

**Comment by ladude626** [comment] 2017-06-09 16:02
Maybe the read requests were too fast. I tried to reproduce with the debug now this time and don't see the issue anymore. Thanks!

**Closed** 2017-06-09 16:02 UTC
Labels: not reproducible
