### ISSUE TITLE
Could Not Write Chunk Temp File - V3.0.0

### ISSUE THREAD

**Issue by lloydie2009** [dweidenfeld/plexdrive#122] opened 2017-05-21 19:59 UTC
Hello,

Wondered if anyone could look at the below and let me know if this is something failing with plexdrive, or something else i can look into.

I'm running Ubuntu 14.04 and seems to only happen on a library scan.

Maybe 90% of the scan seems to work fine, with this coming up every now and then.

Thanks

[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : open /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0: no such file or directory
[PLEXDRIVE] [2017-05-21 19:56] WARNING: Could not write chunk temp file /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0
[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : Requesting object 0B9FTkLZ5jUPAQlNwUWx3dThyazg bytes 0 - 41943040 from API
[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : open /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0: no such file or directory
[PLEXDRIVE] [2017-05-21 19:56] WARNING: Could not write chunk temp file /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0
[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : Requesting object 0B9FTkLZ5jUPAQlNwUWx3dThyazg bytes 0 - 41943040 from API
[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : open /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0: no such file or directory
[PLEXDRIVE] [2017-05-21 19:56] WARNING: Could not write chunk temp file /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0
[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : Requesting object 0B9FTkLZ5jUPAQlNwUWx3dThyazg bytes 0 - 41943040 from API
[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : open /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0: no such file or directory
[PLEXDRIVE] [2017-05-21 19:56] WARNING: Could not write chunk temp file /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0
[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : Requesting object 0B9FTkLZ5jUPAQlNwUWx3dThyazg bytes 0 - 41943040 from API
[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : open /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0: no such file or directory
[PLEXDRIVE] [2017-05-21 19:56] WARNING: Could not write chunk temp file /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0
[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : Requesting object 0B9FTkLZ5jUPAQlNwUWx3dThyazg bytes 0 - 41943040 from API
[PLEXDRIVE] [2017-05-21 19:56] DEBUG  : open /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0: no such file or directory
[PLEXDRIVE] [2017-05-21 19:56] WARNING: Could not write chunk temp file /vol1/tmp/chunks/0B9FTkLZ5jUPAQlNwUWx3dThyazg/0

**Comment by mitchelp** [comment] 2017-05-22 05:51
Ask around on out slack channel. Github is just for programmable issues, not for support.
This could be related to permissions or space. Maybe start over with your cache and chunks.

If you need further assistance ask around on slack.

**Comment by Em31Et** [comment] 2017-05-22 07:54
@mitchelp 
I can confirm it is not the permissions or space issue.
If plexdrive **cleaning empty directory when requesting object**, this warning may occured.
Plexdrive will request from api, retry and faiil write the chunk forever until stop plexdrive manually. (never success)

![screenshot_2017-05-22 15 46 29](https://cloud.githubusercontent.com/assets/18291202/26297718/ad39c0ca-3f06-11e7-8606-726ef8486eeb.png)

**Comment by mitchelp** [comment] 2017-05-22 08:07
@dweidenfeld can you please take a look here. Reopened 👍

**Comment by jrarseneau** [comment] 2017-05-22 21:25
Saw this as well on 3.0, had to revert to 2.0

**Comment by onedr0p** [comment] 2017-05-23 14:12
I had this problem as well, downgraded to 2.1.1 for now.

**Comment by aus** [comment] 2017-05-23 16:22
It can't write the chunk, because the parent directory does not exist. As a workaround, you can `mkdir` the missing directory and things will stabilize.

**Comment by haljordan2814** [comment] 2017-05-23 20:45
I went to 2.1.1 and the issues went away. 2.0 fine as well. Frankly at this point , probably best to stop being frustrated with 3.0.0 and go back to either of those.

**Comment by seuffert** [comment] 2017-05-24 23:16
tested with this and seemed to help :)

https://github.com/seuffert/plexdrive/commit/4a38b6f37f7c5611e83bc68338aee6af6fe020a9

**Comment by jerblack** [comment] 2017-05-25 02:39
Can someone point to a release where this change is integrated or provide step by step instructions on how to do it myself? I saw that contribute blurb on the front page but that wasn't really helpful for something like this.

**Comment by Em31Et** [comment] 2017-05-25 08:59
@jerblack
If you don't want to edit source ode and you are using **--clear-chunk-max-size** ,
you can use **--clear-chunk-age** with a very large value to prevent this bug haapen.

**Comment by dweidenfeld** [comment] 2017-05-26 16:06
Fixed in next release.

**Closed by dweidenfeld** 2017-05-26 16:06 UTC
Labels: bug
