### ISSUE TITLE
Cant delete folders

### ISSUE THREAD

**Issue by emreuenal** [dweidenfeld/plexdrive#78] opened 2017-05-15 17:49 UTC
Hi,

i am using release 2.1.1

I am able to delete files from my mount but cant delete any folder:

`rm -fr /path to mount/testfolder`
`rm: cannot remove ‘testfolder’: Is a directory`

Thx

**Comment by animosity22** [comment] 2017-05-15 18:55
There isn't write support so I'm not sure how you can delete things:

```
felix@plex:/GD$ rm .exists_and_writeable
rm: cannot remove '.exists_and_writeable': Read-only file system
```

**Comment by emreuenal** [comment] 2017-05-15 19:02
From Changelog of 2.1.0:

> Delete files and folders

**Comment by dweidenfeld** [comment] 2017-05-16 06:08
I will try to reproduce the issue. If there is a bug I will fix it for the next release.

**Comment by dweidenfeld** [comment] 2017-05-16 09:14
```
$ ./plexdrive -v2 /tmp/drive
$ cd /tmp/drive

$ ll a
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 a
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 b
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 c
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 d
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 e
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 f
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 g
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 h

$ rm -f a/a

$ ll a
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 b
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 c
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 d
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 e
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 f
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 g
-rw-r--r-- 1 dweidenfeld users 0 May 16 11:06 h

$ rm -rf a

$ ll a
ls: cannot access 'a': No such file or directory
```

@emreuenal 
Everything is working fine for me. Please mount with -v3 as a parameter and send me some error logs.
There is no option --read-only. It is implemented as fuse option: ```-o read_only```

Please also check your global fuse configuration, maybe you disabled some writing options.

I will close this issue now because there is no actual bug. If we find out, that there is a bug for you I will reopen the issue.

**Closed by dweidenfeld** 2017-05-16 09:14 UTC
Labels: bug

**Comment by emreuenal** [comment] 2017-05-16 14:06
@dweidenfeld 

Thank you for your response.

If the folder is an empty folder is or if no another folders in this folder is, i can delete it with` rm -rf folderName`.

If not, i can delete it only wiht `rm -rf folderName/* && rm -rf folderName` .

Should i not be able to delete it just with `rm -rf folderName` ?

```
$ ./plexdrive-linux-amd64 -v2 /tmp/drive/
$ cd /tmp/drive/
$ ll
drwxr-xr-x 1 emreunal psacln 0 May 16 15:36 a
drwxr-xr-x 1 emreunal psacln 0 May 16 15:36 b

$ ll b/
-rw-r--r-- 1 emreunal psacln 0 May 16 15:38 someFile.txt
drwxr-xr-x 1 emreunal psacln 0 May 16 15:38 subFolder

$ rm -fr b
rm: cannot remove ‘b/subFolder’: Is a directory

$ ll b/
drwxr-xr-x 1 emreunal psacln 0 May 16 15:38 subFolder

$ rm -fr b/* && rm -fr b/

$ $ ll /tmp/drive/
drwxr-xr-x 1 emreunal psacln 0 May 16 15:36 a
```

On my first try to `rm -fr b/` i am getting:

```
[PLEXDRIVE-LINUX-AMD64] [2017-05-16 15:38] WARNING: Could not find children for parent 0B8cK-xuYKtdWd1luVjJfTjB6U28 in cache
```

Thank you.

**Comment by RaymondSchnyder** [comment] 2017-11-19 15:56
I have the samle problem, i get always this:

WARNING: Could not delete object 0B66aS2JWbHoJOXR6RG45d3hYaGs (oopq969l44q8ok4mcn2a97k5mn91efrjen7o7j9mh8nn0qt7n7mkpu3uk8i73qr62c118k1urj9vkn578aku708d7br93k990d50lnf5gu6ev06spu8534ng9ba5srbr) from API 
with various filenames of course
